-- ########################################################
-- # Maintainer: Mr. Charkuils                            #
-- # URL:        https://github.com/charkuils/nvim-whisky #
-- ########################################################

return {
    set_groups = function(highlights)
        return {
            Normal                = highlights.hi_1,
            CursorLine            = highlights.hi_1,
            WildMenu              = highlights.hi_1,
            Pmenu                 = highlights.hi_1,
            ModeMsg               = highlights.hi_1,
            MoreMsg               = highlights.hi_1,
            Structure             = highlights.hi_1,
            Macro                 = highlights.hi_1,
            Function              = highlights.hi_1,
            Typedef               = highlights.hi_1,
            DiagnosticUnnecessary = highlights.hi_1,
            CursorLineNR          = highlights.hi_2,
            Title                 = highlights.hi_2,
            Boolean               = highlights.hi_3,
            SpecialKey            = highlights.hi_4,
            Identifier            = highlights.hi_4,
            PreProc               = highlights.hi_5,
            Include               = highlights.hi_5,
            Define                = highlights.hi_5,
            PreCondit             = highlights.hi_5,
            Type                  = highlights.hi_6,
            StorageClass          = highlights.hi_6,
            Repeat                = highlights.hi_6,
            Conditional           = highlights.hi_6,
            Exception             = highlights.hi_6,
            htmlTag               = highlights.hi_6,
            htmlEndTag            = highlights.hi_6,
            htmlTagName           = highlights.hi_6,
            String                = highlights.hi_7,
            Keyword               = highlights.hi_7,
            Operator              = highlights.hi_8,
            Label                 = highlights.hi_8,
            Statement             = highlights.hi_8,
            Special               = highlights.hi_9,
            Tag                   = highlights.hi_9,
            SpecialChar           = highlights.hi_9,
            Delimiter             = highlights.hi_9,
            SpecialComment        = highlights.hi_9,
            Debug                 = highlights.hi_9,
            htmlArg               = highlights.hi_9,
            Number                = highlights.hi_10,
            Character             = highlights.hi_10,
            Float                 = highlights.hi_10,
            Search                = highlights.hi_11,
            IncSearch             = highlights.hi_11,
            NonText               = highlights.hi_12,
            Comment               = highlights.hi_13,
            linenr                = highlights.hi_14,
            MatchParen            = highlights.hi_15,
            Constant              = highlights.hi_16,
            Error                 = highlights.hi_17,
            ErrorMsg              = highlights.hi_18,
            Visual                = highlights.hi_19,
            PmenuSel              = highlights.hi_20,
            WarningMsg            = highlights.hi_21,
            Underline             = highlights.hi_22,
            Annotation            = highlights.hi_23,
            EnumConst             = highlights.hi_24,
            TODO                  = highlights.hi_25,
            SignColumn            = highlights.hi_26,
            VertSplit             = highlights.hi_27,
            StatuslineNC          = highlights.hi_28,
            NormalItalic          = highlights.hi_29
        }
    end
}
