syn match cBraces	 '[\[\]{}=]'
syn match cSign		 '!='
syn match cSign  	 '[+*-]'
syn match cSign  	 '[&|%^]'
syn match cSign  	 '+='
syn match cSign  	 '-='
syn match cSign  	 '*='
syn match cSign  	 '/='
syn match cSign  	 '<='
syn match cSign  	 '>='
syn match cSign  	 '>'
syn match cSign  	 '<'
syn match cSign 	 ' / '
syn match cSign 	 '->'
